award/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^$', views.index, name='index'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^search/', views.search_results, name='search_results'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),

    url(r'^project/$', views.upload_project, name='upload_project'),
    url(r'^user/(\d+)$', views.profile, name='profile'),
    url(r'^profile/update/$', views.update_profile, name='update_profile'),
    url(r'^api/projects/$', views.ProjectList.as_view()),
    url(r'api/projects/project-id/(?P<pk>[0-9]+)/$',
        views.ProjectDescription.as_view()),
    url(r'^api/profiles/$', views.ProfileList.as_view()),
    url(r'api/profiles/profile-id/(?P<pk>[0-9]+)/$',
        views.ProfileDescription.as_view()),
    url(r'^post/(?P<project_id>[0-9]+)/review_design/$',
        views.rate_design, name='rate_design'),
    url(r'^post/(?P<project_id>[0-9]+)/review_usability/$',
        views.rate_usability, name='rate_usability'),
    url(r'^post/(?P<project_id>[0-9]+)/review_content/$',
        views.rate_content, name='rate_content'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

awards/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth import views
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('award.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^api-token-auth/', obtain_auth_token)



]

award/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
import numpy as np
from tinymce.models import HTMLField



class Profile(models.Model):
    '''
    class that contains user Profile properties
    '''
    profile_pic = models.ImageField(upload_to='images/', null=True, blank=True)
    bio = models.TextField()
    contact = models.IntegerField(blank=True, null=True,)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)

    def __str__(self):
        return self.bio

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    post_save.connect(save_user_profile, sender=User)

    def save_profile(self):
        self.save()

    def update_profile(self):
        self.update()

    def delete_profile(self):
        self.delete()

    @classmethod
    def get_profile_by_id(cls, id):
        user_profile = Profile.objects.get(user=id)
        return user_profile

    @classmethod
    def get_profile_by_username(cls, user):
        profile_info = cls.objects.filter(user__contains=user)
        return profile_info

    @classmethod
    def filter_by_id(cls, id):
        profile = Profile.objects.filter(user=id).first()
        return profile


class Project(models.Model):
    '''
    class that contains Project properties
    '''
    title = models.CharField(max_length=40, null=True, blank=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)
    posted_on = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    link = models.URLField(max_length=70)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, default="", blank=True, null=True)
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, default="", blank=True, null=True)
    rating = models.TextField()

    def save_project(self):
        self.save()

    def update_project(self):
        self.update()

    def delete_project(self):
        self.delete()

    class Meta:
        ordering = ['posted_on']

    @classmethod
    def search_project(cls, title):
        project = cls.objects.filter(title__icontains=title)
        return project

    @classmethod
    def get_posted_projects(cls):
        projects = Project.objects.all()
        return projects

    @classmethod
    def get_projects_on_profile(cls, profile):
        projects = Project.objects.filter(profile__pk=profile)
        return projects

    @classmethod
    def get_project_by_id(cls, id):
        project = Project.objects.filter(user_id=id).all()
        return project

    def average_design(self):
        total_ratings = list(
            map(lambda x: x.rating, self.designrating_set.all()))
        return np.mean(total_ratings)

    def average_usability(self):
        total_ratings = list(
            map(lambda x: x.rating, self.usabilityrating_set.all()))
        return np.mean(total_ratings)

    def average_content(self):
        total_ratings = list(
            map(lambda x: x.rating, self.contentrating_set.all()))
        return np.mean(total_ratings)

    def __str__(self):
        return self.title

class DesignRating(models.Model):
    CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10')
    )
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(Profile)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=CHOICES, default=0)

class UsabilityRating(models.Model):
    CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10')
    )
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(Profile)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=CHOICES, default=0)

class ContentRating(models.Model):
    CHOICES = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
        (6, '6'),
        (7, '7'),
        (8, '8'),
        (9, '9'),
        (10, '10')
    )
    project = models.ForeignKey(Project)
    pub_date = models.DateTimeField(auto_now_add=True,)
    profile = models.ForeignKey(Profile)
    comment = models.CharField(max_length=200)
    rating = models.IntegerField(choices=CHOICES, default=0)

award/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile,Project,UsabilityRating,DesignRating,ContentRating

class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        exclude =['posted_on','profile','user','rating',]

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']

class ContentForm(forms.ModelForm):
    class Meta:
        model = ContentRating
        fields = ['rating',]

class UsabilityForm(forms.ModelForm):
    class Meta:
        model = UsabilityRating
        fields = ['rating', ]

class DesignForm(forms.ModelForm):
    class Meta:
        model = DesignRating
        fields = ['rating', ]

award/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http  import HttpResponse,Http404,HttpResponseRedirect
from django.contrib.auth import login, authenticate
from .forms import SignupForm,ProjectForm,UpdateProfileForm,DesignForm,UsabilityForm,ContentForm
from .models import Profile,Project,UsabilityRating,DesignRating,ContentRating
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import ProjectSerializer,ProfileSerializer
from rest_framework import status
from .permissions import IsAdminOrReadOnly
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage
from .email import send_welcome_email



#Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your Awwwards account.'
            message = render_to_string('registration/activate_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            return HttpResponse('Please confirm your email address to complete the registration')
    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return HttpResponse('Thank you for your email confirmation. Now you can login your account.''<a href="/accounts/login/"> click here </a>')
    else:
        return HttpResponse('Activation link is invalid!')



@login_required(login_url='/accounts/login/')
def index(request):
  '''
  view function that renders the homepage
  '''
  form=DesignForm()
  projects = Project.get_posted_projects().order_by('-posted_on')

  return render(request,'index.html',locals())

@login_required(login_url='/accounts/login/')
def search_results(request):
  if 'project' in request.GET and request.GET["project"]:
    form=DesignForm()
    title = request.GET.get("project")
    searched_projects = Project.search_project(title)
    message = f"{title}"

    return render(request, 'search.html',{"message":message,"projects":searched_projects,"form":form})

  else:
    message = "You haven't searched for anything"
    return render(request, 'search.html',{"message":message})

@login_required(login_url='accounts/login/')
def upload_project(request):
    profile = Profile.objects.all()
    for profile in profile:
      if request.method == 'POST':
          form = ProjectForm(request.POST, request.FILES)
          if form.is_valid():
              add=form.save(commit=False)
              add.profile = profile
              add.user = request.user
              add.save()
              return redirect('index')
      else:
          form = ProjectForm()


      return render(request,'upload.html',locals())

@login_required(login_url='/accounts/login/')
def profile(request, user_id):
    '''
    Function that enables users see their profile
    '''
    form=DesignForm()
    title = "Profile"
    projects = Project.get_project_by_id(id= user_id).order_by('-posted_on')
    profiles = Profile.objects.get(user_id=user_id)
    users = User.objects.get(id=user_id)

    return render(request, 'profile/profile.html',locals())


@login_required(login_url='/accounts/login/')
def update_profile(request):
    '''
    Function that enables one to update their profile details
    '''
    current_user = request.user
    profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        form = UpdateProfileForm(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = current_user
            profile.save()
        return redirect('index')
    else:
        form = UpdateProfileForm()
    return render(request, 'profile/update_profile.html', locals())


class ProjectList(APIView):
    def get(self, request, format=None):
        all_projects = Project.objects.all()
        serializers = ProjectSerializer(all_projects, many=True)
        return Response(serializers.data)

    permission_classes = (IsAdminOrReadOnly,)
    def post(self, request, format=None):
        serializers = ProjectSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

class ProjectDescription(APIView):
    permission_classes = (IsAdminOrReadOnly,)
    def get_project(self, pk):
        try:
            return Project.objects.get(pk=pk)
        except Project.DoesNotExist:
            return Http404

    def get(self, request, pk, format=None):
        project = self.get_project(pk)
        serializers = ProjectSerializer(project)
        return Response(serializers.data)

    def put(self, request, pk, format=None):
        project = self.get_project(pk)
        serializers = ProjectSerializer(project, request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        else:
            return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        project = self.get_project(pk)
        project.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class ProfileList(APIView):
    def get(self, request, format=None):
        all_profiles = Profile.objects.all()
        serializers = ProfileSerializer(all_profiles, many=True)
        return Response(serializers.data)

    permission_classes = (IsAdminOrReadOnly,)
    def post(self, request, format=None):
        serializers = ProfileSerializer(data=request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data, status=status.HTTP_201_CREATED)
        return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

class ProfileDescription(APIView):
    permission_classes = (IsAdminOrReadOnly,)
    def get_profile(self, pk):
        try:
            return Profile.objects.get(pk=pk)
        except Profile.DoesNotExist:
            return Http404

    def get(self, request, pk, format=None):
        profile = self.get_profile(pk)
        serializers = ProfileSerializer(profile)
        return Response(serializers.data)

    def put(self, request, pk, format=None):
        profile = self.get_profile(pk)
        serializers = ProfileSerializer(profile, request.data)
        if serializers.is_valid():
            serializers.save()
            return Response(serializers.data)
        else:
            return Response(serializers.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        profile = self.get_profile(pk)
        profile.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

@login_required(login_url='/login')
def rate_usability(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = UsabilityForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.project = project
            vote.user_name = request.user
            vote.profile = request.user.profile

            vote.save()
        return redirect('index')

    return render(request, 'index.html')

@login_required(login_url='/login')
def rate_design(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = DesignForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.project = project
            vote.user_name = request.user
            vote.profile = request.user.profile

            vote.save()
        return redirect('index')
    else:
        form = DesignForm()

    return render(request, 'index.html',locals())


@login_required(login_url='/login')
def rate_content(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.method == 'POST':
        form = ContentForm(request.POST)
        if form.is_valid():
            vote = form.save(commit=False)
            vote.project = project
            vote.user_name = request.user
            vote.profile = request.user.profile

            vote.save()
        return redirect('index')

    return render(request, 'index.html')

award/templates/base.html
{% load bootstrap3 %}
{% load bootstrap4 %}
{%load static%}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">


  {% if title %}
  <title>Awards - {{title}}</title>
  {% else %}
  <title> Awards </title>
  {% endif %}

  {% block styles %}
  {% bootstrap_css %}
  <link rel="shortcut icon" href="/static/photos/w.jpeg" type="image/x-icon">

  {% endblock %}

</head>
<body>
  {% include "navbar.html" %}

  {% block content %}

  {%endblock%}

  {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
</body>
</html>
<style>
  body{
    background: rgb(223, 223, 223);
  }
</style>

award/templates/index.html
{% extends 'base.html'%}
{% load bootstrap3 %}
{% load bootstrap4 %}
{% load static %}

{% block styles %}
{{block.super}}

<link rel="stylesheet" href="{% static 'css/index.css' %}">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">



{% endblock %}
{% block content %}
<br>
<br>

<div class="container">
  <h4 style="text-align:center;font-size: 20px;font-family: 'Lato', sans-serif;color: black;font-weight: bolder;">The awards of design, creativity and innovation on the internet</h4>
  <h4 style="text-align:center;font-size: 20px;font-family: 'Lato', sans-serif;color: black;font-weight: bolder;">Click on the project image to view descriptions and rate the project.</h4>

  <br>
  <div class="row">
    {% for project in projects %}
    <div class="col-xs-12 col-sm-6 col-md-4 projects">
      <div class="thumbnail" style="width:100% !important;border: solid rgb(34, 34, 34);">
        <div class="thumbnail-header">
          <h4 style="font-family: 'Lato', sans-serif;text-align: center;font-size: 20px;color: rgb(69, 182, 69);"><b>{{project.title}}</b></h4>
        </div>
        <img src="{{project.image.url}}"  data-toggle="modal" data-target="#exampleModalCenter{{project.id}}" class = "img-responsive project" alt="" style="height:330px;width: 100% !important;position: center;size: cover;">


        <!-- Modal -->
        <div class="col-xs-12 col-sm-6 col-md-4">
          <div class="modal fade" style="width:100% !important;" id="exampleModalCenter{{project.id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-lg modal-dialog-centered" role="document">
              <div class="modal-content" style=" font-family: 'Lato', sans-serif !important;background: rgb(29, 29, 29); color:#d6d3cd;">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalCenterTitle" style="font-size:40px;"><b>{{project.title}}</b></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <img src="{{project.image.url}}"  class = "img-responsive" alt="" style="height:500px;width: 100%;">
                </div>
                <div class="modal-body">
                  <br>
                  <br>
                  <p style="font-size:22px;padding-right: 70px;"><b>Posted by:</b> {{project.user}}</p>
                  <p style="font-size:22px;padding-right: 70px;"><b>Posted On:</b> {{project.posted_on}}</p>
                  <p style="font-size:22px;padding-right: 70px;"><b>Description:</b> {{project.description}}</p>
                  <form action="">
                    <b style="font-size:22px;" >Link :</b>&nbsp;&nbsp; <a href="{{project.link}}" style="width:100%;height:40px;font-size: 20px;">{{project.link}}</a>
                    <br>
                  </form>
                  <br>
                  <h4 style="color: whitesmoke;text-decoration-line: underline;">Project Rating Criteria</h4>
                  <h5>{{ project.rating.count }} <h5 style="color: green;">a)Design</h5>  average = {{ project.average_design | floatformat }} </h5>

                  <h5>{{ project.rating.count }} <h5 style="color: green;">b)Usability</h5> average = {{ project.average_usability | floatformat }} </h5>

                  <h5>{{ project.rating.count }} <h5 style="color: green;">c)Content</h5>  average = {{ project.average_content | floatformat }}</h5>
                  <br><br>

                  <div class="col-xs-3 col-sm-6 col-md-4 col-lg-4">
                    <h5>a)Rate By Design</h5>



                    <form  action="{%url 'rate_design' project_id=project.id %}" method="POST">
                      {%csrf_token%}
                      {% bootstrap_form form layout='inline' %}
                      <input type="submit" class="btn-md btn btn-success" style="width:50% !important;" value="Rate">
                    </form>
                    <br>
                    <h5>b)Rate By Usability</h5>
                    <form  action="{%url 'rate_usability' project_id=project.id %}" method="POST">
                      {%csrf_token%}
                      {% bootstrap_form form layout='inline' %}
                      <input type="submit" class="btn-md btn btn-success" style="width:50% !important;" value="Rate">
                    </form>

                    <h5>c)Rate By Content</h5>
                    <form  action="{%url 'rate_content' project_id=project.id %}" method="POST" style="width:100%;">
                      {%csrf_token%}
                      {% bootstrap_form form layout='inline' %}
                      <input type="submit" class="btn-md btn btn-success" style="width:50% !important;" value="Rate">
                    </form>
                    <br>


                  </div>


                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default button" data-dismiss="modal">Close &nbsp;<i class="fas fa-times"></i></button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <br>
    </div>
    {% endfor %}
  </div>
</div>

<style>
  .stars-outer{
    position: relative;
    display: inline-block;
  }
  .stars-inner{
    position: absolute;
    top: 0;
    left: 0;
    white-space: nowrap;
    overflow: hidden;
    width: 0;
  }

  .stars-outer::before {
    content: "\f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005";
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    color: #ccc;
  }

  .stars-inner::before {
    content: "\f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005 \f005";
    font-family: 'Font Awesome 5 Free';
    font-weight: 900;
    color: #f8ce0b !important;
  }
  #id_rating{
    width: 80px !important;
  }
  #id_comment{
    width: 400px !important;
  }
</style>
{% endblock %}
{% block scripts %} {{block.super}}
<script type="text/javascript" src="{%static 'js/ratings.js'%}"></script>
{% endblock %}

award/templates/navbar.html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">

<div class="topnav" id="myTopnav">
    <a href="/">Home&nbsp;<i class="fas fa-home"></i></a>
    <a href="/user/{{user.id}}">Profile&nbsp;<i class="fas fa-user-circle"></i></a>
    <a href="{% url 'update_profile' %}">Edit Profile &nbsp;<i class="fas fa-user-edit"></i></a>
    <a href="{% url 'upload_project' %}">Add Project&nbsp;<i class="fas fa-plus"></i></a>
    <a href="" data-toggle="modal" data-target="#myModal">Accounts&nbsp;<i class="fas fa-user-cog"></i></a>

    <!-- Modal -->
    <div class="modal fade" style="padding-top: 250px;" id="myModal" role="dialog">
        <div class="modal-dialog modal-sm">

            <!-- Modal content-->
            <div class="modal-content">

                <button type="button" class="close" data-dismiss="modal">&times;</button>

                <li class="list-group-item text-center"><a style="color:black;"  href="/accounts/password/change">Change Password</a></li>
                <hr>

                <li class="list-group-item text-center"><a style="color:black;" href="/logout/">Log Out</a></li>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
            </div>

        </div>
    </div>
    <form class="navbar-form search" role="search" action="{% url 'search_results' %}" style="padding-right:50px !important;">

        <div class="input-group" style="width:170px;">
            <input type="text" class="form-control" id="search" placeholder=" &#xF002; search project by title" name="project">
        </div>

    </form>
    <a href="/user/{{user.id}}" style="float:right !important;font-size: 17px;"><i class="fas fa-user"></i>&nbsp;&nbsp;{{user.username}}</a>
    <a href="javascript:void(0);" class="icon" onclick="myFunction()">
        <i class="fa fa-bars"></i>
    </a>

</div>

<style>
    /* Add a black background color to the top navigation */
    .topnav {
        background-color: #333;
        overflow: hidden;
        font-family: 'Lato', sans-serif;
    }

    /* Style the links inside the navigation bar */
    .topnav a {
        float: left;
        display: block;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }

    /* Change the color of links on hover */
    .topnav a:hover {
        background-color: rgb(69, 182, 69);
        color: black;
    }

    /* Add an active class to highlight the current page */
    .active {
        background-color: #4CAF50;
        color: white;
    }

    /* Hide the link that should open and close the topnav on small screens */
    .topnav .icon {
        display: none;
    }

    .search {
        float: right !important;
    }
    #search{
        font-family:FontAwesome !important;
    }
    ::placeholder{
        font-size: 15px;
    }
</style>

award/templates/upload.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<br>
<br>
<div class="container" style="font-family: 'Lato', sans-serif;font-size: 17px;">
    <div class="row">
        <div class="col-md-8">
            <form action="{% url 'upload_project' %}" method="POST" enctype="multipart/form-data" style="font-weight:bold !important;">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-success btn-md" value="POST">
            </form>
        </div>
    </div>
</div>
{{ form.media }}
{% endblock %}